version: '3.7'

services:
  leon:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    depends_on:
      - leon-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://leon-database:5432/leon
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  leon-database:
    image: postgres:alpine3.14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leon